### ISSUE TITLE
IPv6 support [6182]

### ISSUE THREAD

**Issue by adamkrawczyk** [eProsima/Micro-XRCE-DDS-Agent#107] opened 2019-08-06 08:11 UTC
Hi, 

I'm trying to match this with [husarnet](https://husarnet.com/) ,  (esp32) , but it seems like this version has no ipv6 support. Does it? and how to use that? . I had similar problem with rosserial but I found what needs to be changed to enable that. Thank you in advance :)

versions: 

|ros2arduino|ROS2|Micro-XRCE-DDS Agent|
|:-:|:-:|:-:|
|0.1.2|[Dashing Diademata Patch1](https://github.com/ros2/ros2/releases/tag/release-dashing-20190614)|[1.1.0](https://github.com/eProsima/Micro-XRCE-DDS-Agent/releases/tag/v1.1.0)|

**Comment by julianbermudez** [comment] 2019-08-06 10:04
Hi @adamkrawczyk,

There is a branch under development (in both [Client](https://github.com/eProsima/Micro-XRCE-DDS-Client/tree/feature/ipv6) and [Agent](https://github.com/eProsima/Micro-XRCE-DDS-Agent/tree/feature/ipv6)) which implements IPv6. You can try with it a give us feedback. Thanks!

**Comment by adamkrawczyk** [comment] 2019-08-06 11:13
There is problem with make - after cloning this branch 

`git clone --single-branch --branch feature/ipv6 https://github.com/eProsima/Micro-XRCE-DDS-Agent.git` 

when i try to `make` i have following error:

![make_problem_eprosima](https://user-images.githubusercontent.com/29305346/62535562-04db0a80-b84c-11e9-992e-46fc2aadb680.png)

**Comment by julianbermudez** [comment] 2019-08-06 12:22
Do you have Micro XRCE-DDS Client installed on your computer?
It seems to be a compatibility version error. Try to uninstall it and install the IPv6 branch version.

**Comment by adamkrawczyk** [comment] 2019-08-06 12:40
No I don't have. I even installed Client and everything compiled correctly but agent is still not working

**Comment by adamkrawczyk** [comment] 2019-08-06 13:00
I've tested that on another computer where any version was never downloaded and I have following error:
```
[ 92%] Building CXX object CMakeFiles/microxrcedds_agent.dir/src/cpp/p2p/InternalClient.cpp.o
/home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/src/cpp/p2p/InternalClient.cpp: In member function ‘bool eprosima::uxr::InternalClient::run()’:
/home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/src/cpp/p2p/InternalClient.cpp:107:83: error: invalid conversion from ‘uint16_t {aka short unsigned int}’ to ‘const char*’ [-fpermissive]
         if (uxr_init_udp_transport(&transport_, &platform_, UXR_IPv4, ip.c_str(), port_))
                                                                                   ^~~~~
In file included from /home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/build/temp_install/include/uxr/client/transport.h:21:0,
                 from /home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/build/temp_install/include/uxr/client/client.h:30,
                 from /home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/include/uxr/agent/p2p/InternalClient.hpp:18,
                 from /home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/src/cpp/p2p/InternalClient.cpp:15:
/home/byq77/workspace/tmp/Micro-XRCE-DDS-Agent/build/temp_install/include/uxr/client/profile/transport/ip/udp/udp_transport.h:48:16: note:   initializing argument 5 of ‘bool uxr_init_udp_transport(uxrUDPTransport*, uxrUDPPlatform*, uxrIpProtocol, const char*, const char*)’
 UXRDLLAPI bool uxr_init_udp_transport(
                ^~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/microxrcedds_agent.dir/build.make:878: recipe for target 'CMakeFiles/microxrcedds_agent.dir/src/cpp/p2p/InternalClient.cpp.o' failed
make[5]: *** [CMakeFiles/microxrcedds_agent.dir/src/cpp/p2p/InternalClient.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/microxrcedds_agent.dir/all' failed
make[4]: *** [CMakeFiles/microxrcedds_agent.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/uagent.dir/build.make:115: recipe for target 'uagent-prefix/src/uagent-stamp/uagent-build' failed
make[2]: *** [uagent-prefix/src/uagent-stamp/uagent-build] Error 2
CMakeFiles/Makefile2:256: recipe for target 'CMakeFiles/uagent.dir/all' failed
make[1]: *** [CMakeFiles/uagent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

the same file but this time the problem is with port_

**Comment by julianbermudez** [comment] 2019-08-07 05:49
Hi @adamkrawczyk,

That compilation error should be fixed now.

**Comment by adamkrawczyk** [comment] 2019-08-07 12:09
It's working now :) I'm waiting for tcp6 for ESP32

**Comment by adamkrawczyk** [comment] 2019-08-08 08:51
If only this will be useful I have following troubles:
![eprosima_node_problem](https://user-images.githubusercontent.com/29305346/62689116-79d44e80-b9ca-11e9-8681-5500ae723561.png)

**Comment by julianbermudez** [comment] 2019-08-27 08:45
Hi @adamkrawczyk, 

Sorry for the delay but we were on vacations. Are you able to reproduce the same error using IPv4?

**Comment by adamkrawczyk** [comment] 2019-08-28 12:36
I've tried and I have the same error when using tcp4

**Comment by adamkrawczyk** [comment] 2019-08-28 12:57
I also have this error when using serial connection, but I'm able to list topic and see this topic 

```
adam@adamlaptop:~$ ros2 node list
/ros2arduino_pub_node
adam@adamlaptop:~$ ros2 node info /ros2arduino_pub_node 
/ros2arduino_pub_node
[ERROR] [rmw_fastrtps_shared_cpp]: Unable to find GUID for node: ros2arduino_pub_node
Failed to get_subscriber_names_and_types: Unable to find GUID for node , at /tmp/binarydeb/ros-dashing-rmw-fastrtps-shared-cpp-0.7.5/src/rmw_node_info_and_types.cpp:87
adam@adamlaptop:~$ ros2 topic list
/arduino_chatter
/parameter_events
/rosout
adam@adamlaptop:~$ ros2 topic echo /arduino_chatter 
data: Hello ros2arduino 69
---
data: Hello ros2arduino 70
---

**Comment by BorjaOuterelo** [comment] 2019-11-18 08:37
Hi @adamkrawczyk are you still having this issue?

**Comment by julibert** [comment] 2020-03-06 07:20
Hi @adamkrawczyk, I close this issue. In case it persists, please reopen it.

**Closed by julibert** 2020-03-06 07:20 UTC
