### ISSUE TITLE
XRCE messaging protocols

### ISSUE THREAD

**Issue by vibnwis** [eProsima/Micro-XRCE-DDS-Agent#211] opened 2021-02-02 12:12 UTC
Greetings,
Would you mind sharing the concept of uxr_run_session_until_all_status routine, please? It would help me to understand the code and reasoning what goes wrong here.

Very appreciate that!

**Comment by pablogs9** [comment] 2021-02-02 13:24
You can find information about the XRCE Client Session API [here](https://micro-xrce-dds.docs.eprosima.com/en/latest/client.html?highlight=uxr_run_session_until_all_status#session).

As you can see, when a client runs a session until all status, the XRCE client will try to communicate with the agent until all messages sent via reliable stream are confirmed by the Agent.

I'm closing since documentation have been provided, please reopen if you have further doubts.

**Closed by pablogs9** 2021-02-02 13:24 UTC
